### ISSUE TITLE
Don't use assignment for MERGE/Update

### ISSUE THREAD

**Issue by jexp** [neo4j-graphql/neo4j-graphql-java#105]
See the discussion here:

https://github.com/neo4j-graphql/neo4j-graphql-java/pull/99#pullrequestreview-461213019

Switch from `SET x = {...}` to `SET x += {}` or individual set operations.
We could also consider putting the data just into a parameter instead. So it would become `SET x += $data`

> Usually you merge on a single field (in exceptional cases on a set of fields). (they keys that are used to look-up nodes for uniqueness)
> And update fields are the fields that are added/overriden.

> As MERGE is get-or-create you don't want to destroy existing additional data that might have been added in between by other means.

> And if you leave off fields it doesn't mean you want to remove them, just that you don't have data (or updates) for them at the moment.

**Comment by rbramley** [comment]
This causes a critical problem for data that has been loaded from CSV files where the existing external `:ID` field has been retained. 
The result of an update mutation is that the ID field is stripped from the node.

**Comment by Andy2003** [comment]
@rbramley your issue was resolved by https://github.com/neo4j-graphql/neo4j-graphql-java/issues/95
