### ISSUE TITLE
CALL graphql.idl() command not working when schema contains @cypher directive

### ISSUE THREAD

**Issue by Chimba123** [neo4j-graphql/neo4j-graphql-java#111]
I am using Neo4j 3.5.14 with the APOC plugin installed everything else works fine

However, when I try to update the graphql schema with cypher queries using the @cypher directive using `CALL graphql.idl()` it just doesn't work. I have used the example schema here https://neo4j.com/developer/graphql/
it still doesn't work.

**Comment by jexp** [comment]
Are you using the database plugin or this middleware library?

Can you share your script / screenshot?

What does "doesn't work" mean?

**Comment by Chimba123** [comment]
@jexp 
locally I am using the plugin installed automatically from the plugin section then for my sandbox I am using a graphene database with the Full APOC installed.

In both cases, the command is not working when I use the "@cypher" directive 

the code is as follows
`graphql.idl(“      
type User {       
followsCount:Int @cypher (
statement: "MATCH (this)<-[r:FOLLOWS_ON_SOCIALS]-(:User) with this, count(r) as rel_cnt return rel_cnt"
)
}
“)`

I am getting the following error:
Neo.ClientError.Statement.SyntaxError
Invalid input 'M': expected whitespace, '.', node labels, '[', "=~", IN, STARTS, ENDS, CONTAINS, IS, '^', '*', '/', '%', '+', '-', '=', '~', "<>", "!=", '<', '>', "<=", ">=", AND, XOR, OR, ',' or ')' (line 20, column 13 (offset: 574)) "statement: "MATCH (this)<-[r:FOLLOWS_ON_SOCIALS]-(:User) with this, count(r) as rel_cnt return rel_cnt"

**Comment by Chimba123** [comment]
@jexp no working means it's not setting the schema when the "@cypher" directive is in the command and frankly it's disturbing

I have realized all the examples where the @cypher directive is used that you guys give are not used with `CALL graphql.idl()` as a wrapper... perhaps there is a special of doing it in graphql that you guys are not showing?

take for example the link given above it just shows the schema... but not the procedure command to create the schema

**Comment by Chimba123** [comment]
@jexp ITS NOT WORKING AND THE INSTRUCTIONS WRT GRAPHQL JAVA and the `CALL graphql.idl()` command are not clearly shown only raw schema objects are shown but not with the command ... something is off ...

**Comment by jexp** [comment]
You saw that you were using double quotes within double quotes?
You should use single quotes on the procedure call string.

Also this is the wrong repo, the correct repo for the plugin is github.com/neo4j-graphql/neo4j-graphql

`graphql.idl(' type User { followsCount:Int @cypher ( statement: "MATCH (this)<-[r:FOLLOWS_ON_SOCIALS]-(:User) with this, count(r) as rel_cnt return rel_cnt" ) } ')
`

**Comment by Chimba123** [comment]
@jexp you mean I should just use single quotes throughout? I am not quite clear...   because I am surprised that very command all of sudden has just started working... I am confused

**Comment by Chimba123** [comment]
> You saw that you were using double quotes within double quotes?
> You should use single quotes on the procedure call string.
> 
> Also this is the wrong repo, the correct repo for the plugin is github.com/neo4j-graphql/neo4j-graphql
> 
> `graphql.idl(' type User { followsCount:Int @cypher ( statement: "MATCH (this)<-[r:FOLLOWS_ON_SOCIALS]-(:User) with this, count(r) as rel_cnt return rel_cnt" ) } ') `

Thanks a lot !!! wow what a simple solution!!
