### ISSUE TITLE
Question re deleting relationships

### ISSUE THREAD

**Issue by michael-forman** [neo4j-graphql/neo4j-graphql-java#112]
I have a simplified schema of:
```
type User
{
  name: String!
  uuid: ID!
  associates: [User!] @relation(name:"ASSOCIATES_WITH",direction:BOTH)
}
```

specifically the direction is BOTH, meaning I'm attempting a "symmetrical" relationship.

This is working fine in so much as when I create a graph like:

![Users](https://user-images.githubusercontent.com/12082333/90704961-3434ac00-e2d5-11ea-88f5-32afdcb06751.png)

the query like `query { user(uuid: $uuid) { uuid, name, associates { name uuid } } }` for the uuid for "Fred" will return both "Pete" and "Harry", which are out and in links respectively.

The mutation for deleting `deletePersonAssociates` is still "directional", in that it takes the ID (uuid in my case) of the "from" side of a link, and the list of IDs of associates to delete.  In order to use this I must know the direction still.  ie from the ID (uuid) of "Fred" in my graph I can not delete the link to "Harry".  In order to delete the link between Fred and Harry I need to do deletePersonAssociates using the ID of the "from" side, so Harry to Fred.

Not sure if this is deliberate, but it means that my "application" layer still needs to understand the directionality of the links.

Have I missed something here?

Cheers,

Michael

**Comment by Andy2003** [comment]
The generated Cypher for your issue is correct:

Schema

```graphql
type User
{
  name: String!
  uuid: ID!
  associates: [User!] @relation(name:"ASSOCIATES_WITH", direction:BOTH)
}
```

Data:

```cypher
CREATE
    (pete:User{ name: 'Pete', uuid: '1' }),
    (fred:User{ name: 'Fred', uuid: '2' }),
    (harry:User{ name: 'Harry', uuid: '3' }),
    (pete)<-[:ASSOCIATES_WITH]-(fred),
    (fred)<-[:ASSOCIATES_WITH]-(harry)
```

Mutation

```graphql
mutation {
  deleteUserAssociates(uuid: "2", associates: ["1", "3"]) {
    name
    associates { name uuid }
  }
}
```

Generated Cypher:

```cypher
MATCH (from: User { uuid: $fromUuid })
MATCH (to: User) WHERE to.uuid IN $toAssociates
MATCH (from)-[r: ASSOCIATES_WITH]-(to)
DELETE r
WITH DISTINCT from AS deleteUserAssociates
RETURN deleteUserAssociates {
    .name,
    associates: [(deleteUserAssociates)-[: ASSOCIATES_WITH]-(deleteUserAssociatesAssociates: User) | deleteUserAssociatesAssociates {
        .name,
        .uuid
    }]
} AS deleteUserAssociates
```

I guess it was fixed by https://github.com/neo4j-graphql/neo4j-graphql-java/pull/107 (#98)
