### ISSUE TITLE
Update graphql-java to 15.0

### ISSUE THREAD

**Issue by claymccoy** [neo4j-graphql/neo4j-graphql-java#118]
This project hasn't had a release in a while and even on master it uses an old version of graphql-java. This becomes an issue when you want to use another project that also depends on graphql-java and it is a newer version.
I'm specifically trying to use this with the [graphql-kotlin-schema-generator](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/graphql-kotlin-schema-generator) which uses graphql-java version 15. There is a pretty cool use case to generate the schema from my application's Neo4j object model and then use neo4j-graphql-java to translate the queries to Cypher. But as of right now the two libraries are incompatible because of the different versions.
Is there an issue with updating this dependency? Would it be possible to do that an make a new release?
Thanks,
Clay

**Comment by claymccoy** [comment]
I put together a PR to update graph-java #120. It required a fair amount of changes to both code and unit tests though. You probably want to check over what I did.
This project is great, but the adoption of it will be stifled unless you keep up to date with graphql-java or preferably remove that dependency. The author of it seems to enjoy making backwards-incompatible changes.

**Comment by jexp** [comment]
Thanks a lot @claymccoy for your feedback and contribution. Much appreciated!!

**Comment by Andy2003** [comment]
Resolved by #120 
We have created a [branch `1.0`](https://github.com/neo4j-graphql/neo4j-graphql-java/tree/1.0) and released [version 1.0.1](https://github.com/neo4j-graphql/neo4j-graphql-java/releases/tag/1.0.1 ) to be compatible with `graphql-java` version 12

The master will be compatible with `graphql-java` version 15. We released these changes with [version 1.1.0](https://github.com/neo4j-graphql/neo4j-graphql-java/releases/tag/1.1.0)
