### ISSUE TITLE
generated cypher does not validate with M15 openCypher grammar

### ISSUE THREAD

**Issue by crichey** [neo4j-graphql/neo4j-graphql-java#131]
Hi. I'm testing this with VERY simple GQL and the resulting cypher does not seem to validate with the M15 openCypher grammar. One such example of generated cypher is below:

MATCH (election:Election) WHERE election.electionName = $electionElectionName
RETURN election { .electionDate } AS election

The grammar chokes on the { in the return statement.

**Comment by jexp** [comment]
Opencypher doesnt have all features of neo4j cypher like pattern comprehensions, map projections or procedure calls. 

Not sure why not.

**Comment by crichey** [comment]
Well, yes, I'm aware of that. However, don't you think the project would be more useful if it generated cypher that conformed to the specification?

**Comment by jexp** [comment]
Then many basic features of the transpiler would not be possible. 

Sorry openCypher was not a target for this one.
