### ISSUE TITLE
Incorrect query translation for @property(name:"testIds.uuid")

### ISSUE THREAD

**Issue by mdiadia-rft** [neo4j-graphql/neo4j-graphql-java#160]
Hello

Given type:
```
type User {
    userId: ID!
    uuid: String @property(name:"testIds.uuid")
}
```

And GraphQL query:
```
{
  user(filter: {uuid:"test-uuid"}) {
    userId
    uuid
  }
}
```

Method translate generates wrong filter condition(WHERE section), using method translate into class Translator.kt:
```
MATCH (user:User) 
WHERE user.uuid= 'test-uuid'
RETURN user { .userId, uuid:user.`testIds.uuid`} AS user
```

But query should be:
```
MATCH (user:User) 
WHERE user.`testIds.uuid`= 'test-uuid'
RETURN user { .userId, uuid:user.`testIds.uuid`} AS user
```

Actual result: empty object is returned.

Possible places to fix:
Predicates.kt#toExpression line 120 
Predicates.kt#resolvePredicate line 33(be aware about dots in filter placeholders)

Thanks

**Comment by Andy2003** [comment]
Resolved by #171
