### ISSUE TITLE
problem with optimized FILTER_AS_MATCH strategy

### ISSUE THREAD

**Issue by limejuly** [neo4j-graphql/neo4j-graphql-java#163]
Back ground: version 1.2.0,  using FILTER_AS_MATCH strategy
Problem: Querying any argument that is not "filter" will be ignored.
for example, what I query is:
```
{
  product(id:"product8") {
     id
  }
}
```
And the "id" argument is ignored.

In the previous version, non filter arguments will make FILTER_AS_MATCH fail, so one can fall back to normal strategy. But now it is not failing, neither does it handle them.

Is that the expected behavior or am I using it wrong?

The corresponding change is #153

**Comment by Andy2003** [comment]
@limejuly can you create [a test case](https://github.com/neo4j-graphql/neo4j-graphql-java/tree/master/core/src/test/resources/issues) for your issue please

**Comment by limejuly** [comment]
@Andy2003 Hello, I have created a test case, please let me know if it is not valid.
