### ISSUE TITLE
Please add passThrough=true support!

### ISSUE THREAD

**Issue by n2iw** [neo4j-graphql/neo4j-graphql-java#190]
We are using Neo4j-GraphQL plugin in production. And we  are in the process of migrating to Neo4j-GraphQL-Java. Our schema uses a lot of "passThrough=true" parameters to return embedded map/objects. Please add this, thanks!

**Comment by Andy2003** [comment]
@n2iw yan you take a look at the PR #195 if it satisfies your needs

**Comment by n2iw** [comment]
Thanks @Andy2003, I've tested PR #195, and left a comment there. Please take a look, thanks!

**Comment by n2iw** [comment]
@Andy2003 thanks for fixing this for us! When can we expect it to be released? Our development is depending on this, thanks!

**Comment by Andy2003** [comment]
@jexp when can create the next release
@n2iw please note that with the next release this library will be upgraded to java 11 and neo4j 4.2
