### ISSUE TITLE
Getting java.lang.NoSuchFieldError: GRAPHQL_SPECIFICATION_SCALARS_DEFINITIONS

### ISSUE THREAD

**Issue by Anunayth** [neo4j-graphql/neo4j-graphql-java#191]
Hello, 

I am trying to run neo4j-graphql-java as a springboot application. I am using the following dependency. 

1. org.neo4j : neo4j-graphql-java (version 1.1.0)
2. org.neo4j.driver : neo4j-java-driver (version 4.1.1)

While building the schema 
`TypeDefinitionRegistry typeRegistry = new TypeDefinitionRegistry();`
`//{some code to set schema file to typeRegistry}`
`GraphQLSchema schema = SchemaBuilder.buildSchema(typeRegistry, schemaConfig); //this is line 139 where exception is throwing`

i get the following error

`Caused by: java.lang.NoSuchFieldError: GRAPHQL_SPECIFICATION_SCALARS_DEFINITIONS
	at org.neo4j.graphql.SchemaBuilder.buildSchema(SchemaBuilder.kt:46)
	at org.neo4j.graphql.SchemaBuilder.buildSchema$default(SchemaBuilder.kt:38)
	at org.neo4j.graphql.SchemaBuilder.buildSchema(SchemaBuilder.kt)
	at project.configuration.CoreAppConfiguration.translator(CoreAppConfiguration.java:139)
	)`

What should I do to resolve this issue?

**Comment by Andy2003** [comment]
@Anunayth 

I guess you use the wrong version of `graphql-java` ensure to have no dependency conflict there!
In  `neo4j-graphql-java:1.1.0` we use `graphql-java:15.0`

**Comment by Anunayth** [comment]
@Andy2003 
changed to `graphql-java:15.0`. No longer getting the exception. 
Thanks.
