### ISSUE TITLE
Support for Map / JSON return type

### ISSUE THREAD

**Issue by Anunayth** [neo4j-graphql/neo4j-graphql-java#199]
Is it possible to use Map or a JSON as the return type for any query? 

eg : 
`getMap(inpVal: ID): <Return Type as Map> @cypher(statement:"call example.procedure($inpVal) yield value return value")`

If the returned value is a map / JSON, then what should I do to get the value.

**Comment by Andy2003** [comment]
Can you take a look at https://github.com/neo4j-graphql/neo4j-graphql-java/pull/195 to see if it fits your needs

**Comment by Anunayth** [comment]
No more required
