### ISSUE TITLE
Confused about relation filters

### ISSUE THREAD

**Issue by yarc** [neo4j-graphql/neo4j-graphql-java#237]
Take this simple schema and query:

```
type User {
  age: Int!
  groups: [UserGroup]
}

type UserGroup {
  uuid: String!
  users: [User]
}
```

```
query {
  userGroup (filter: {users: {age_gt: 30}}) {
    uuid
    users {
      name
    }
  }
}
```

How would i query in order to obtain the list of UserGroups which only have Users over the age of 30? The problem is that everything i try also returns UserGroups that have no Users at all. I think it comes from the fact that the ALL() predicate returns true on an empty list. I'm seeing this class of problem happening in many places in my code and i don't see a way around it.

Many thanks

**Comment by Andy2003** [comment]
@yarc can you please create a test case (like https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/core/src/test/resources/issues/gh-65.adoc) for your issue

**Comment by Andy2003** [comment]
just add it at this issue as comment
