### ISSUE TITLE
CRUD Mutations

### ISSUE THREAD

**Issue by voodoo144** [neo4j-graphql/neo4j-graphql-java#240]
Hi, I'm trying to use Translator to convert graphql queries to cypher and use it in my application.
Schema created like that:
```
TypeDefinitionRegistry typeDefinitionRegistry = new SchemaParser().parse(schemaAsString);

GraphQLSchema schema = SchemaBuilder.buildSchema(typeDefinitionRegistry,
                new SchemaConfig(
                        new SchemaConfig.CRUDConfig(true, Collections.emptyList()),
                        new SchemaConfig.CRUDConfig(true, Collections.emptyList()),
                        false,
                        SchemaConfig.InputStyle.INPUT_TYPE));
```

Schema:

```
type Host {
  hostname: String
  ipAddress: String
}

type Node {
  nodeName: String
  host: Host @relation(name:"BELONGS_TO")
}

type Query {
  node: [Node]
  host: [Host]
  service: [Service]
}

type Service {
  serviceName: String
  node: Node @relation(name:"RUNS_ON")
}
```

Auto generated queries and filters works great-> but for Mutations i see only

 `createHost, createNode, createService`

Do I need to add something else to have

 `addServiceNode, addNodeHost ...` mutations?

**Comment by Andy2003** [comment]
Have you [looked at the tests](https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/core/src/test/resources/relationship-tests.adoc), there you can see how relations can be created

**Comment by voodoo144** [comment]
@Andy2003 yes I saw that, the problem that add* mutations does not exists in schema. 
SchemaBuilder creates only create* mutations

**Comment by voodoo144** [comment]
@Andy2003 
How I can create relations then with only create mutations?
```
createService(serviceName: "service1" ) 
createNode(nodeName: "node1")
```
how I can create relation between them?
For that purpose SchemaBuilder suppose to create add mutations -> but it doesnt.

```
createService(serviceName: "service1" ) 
createNode(nodeName: "node1")
addServiceNode ... -> this one does not exists in schema
```

**Comment by Andy2003** [comment]
For this you need IDs

Alexey Alexeev ***@***.***> schrieb am Mi., 4. Aug. 2021,
16:44:

**Comment by voodoo144** [comment]
After adding `id: ID!` for every object mutations appear!

thanks a lot   @Andy2003
