### ISSUE TITLE
status of the project

### ISSUE THREAD

**Issue by aleksandersumowski** [neo4j-graphql/neo4j-graphql-java#257]
Hi team,
you mention that the JS version of this project has majored into a product, which as I understand means official support and plans to develop. Does it mean this one - the JVM one - hasn't for the time being? Is there a plan to support both?

**Comment by jexp** [comment]
Yes that's correct. 
This library is still under the "Neo4j Labs" umbrella, i.e. no official support (except if a customer contract includes it) and no guarantees/SLAs. There hasn't been made a decision yet about supporting both.

**Comment by aleksandersumowski** [comment]
So there is an option to buy support as part of the contract. Thanks!

And sorry for asking similar questions both here and on Discord
