### ISSUE TITLE
Filtering on multi-relationship existence

### ISSUE THREAD

**Issue by nmonterroso** [neo4j-graphql/neo4j-graphql-java#27]
I'm trying to create a filter that says "where a list of relationships is non-empty". For example, loading a database with:
```
create(n1:Person {name:"foo"}),
    (n2:Person {name:"bar"}),
    (n3:Pet {name:"baz"}),
    (n1)-[:knows]->(n2),
    (n2)-[:knows]->(n3)
```
with the schema:
```
type Person {
	name: String!
	friends: [Person!]! @relation(name:"knows",direction:OUT)
	pets: [Pet!] @relation(name:"knows",direction:OUT)
}

type Pet {
	name: String!
}
```

I want a query that says "find me only the people that `know` a `Person`, regardless of whether or not they `know` any `Pet`s". Based on the filter [documentation](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/test/tck/filterTck.md#related-node-exists) I was hoping to use something like:
```
{
  person (filter: { friends_not: null }) {
    name
    friends {
      name
    }
    pets {
      name
    }
  }
}
```
but this produces the following error: `Input for friends must be an filter-InputType`. I also tried a few different queries:
- `(filter: { friends: { name_not: null } })` - I was hoping this would work indirectly since it would match into the friend node and filter on the name, but that produced this cypher:
  - ```MATCH (person:Person) WHERE  ALL(person_Person_Cond IN [(person)-[:knows]->(person_Person) | (NOT person_Person.name = $filterPerson_PersonName)] WHERE person_Person_Cond) RETURN person { .name,friends:[(person)-[:knows]->(personFriends:Person) | personFriends { .name }],pets:[(person)-[:knows]->(personPets:Pet) | personPets { .name }] } AS person```
  - the `NOT person_Person.name = $filterPerson_PersonName` since `$filterPerson_PersonName` is `null` the query does not get the expected results, and when I manually change it to an `is null`, I also get the unexpected result of both `Person`s.
- `(filter: { friends_not: [] })` - Input for friends must be an filter-InputType

I created [nmonterroso/neo4j-graphql-java-filters](https://github.com/nmonterroso/neo4j-graphql-java-filters) to illustrate this issue.

Any help is greatly appreciated!

EDIT - This also affects the server plugin `neo4j-graphql`, and I've created [neo4j-graphql#177](https://github.com/neo4j-graphql/neo4j-graphql/issues/177) for that side of the equation.

**Comment by jexp** [comment]
Great question,

usually, it would be something like: `friends_none: { name: "Joe" }`

But I think we don't have an operator yet that check existence.
So it would be great to add.

I wonder if an empty `friends_some: {}` would work, but I think graphql doesn't allow empty input types.

**Comment by nmonterroso** [comment]
I added another test to my repo with `friends_some`, and I'm getting the following cypher:
```
MATCH (person:Person) WHERE  ANY(person_Person_Cond IN [(person)-[:knows]->(person_Person) | ] WHERE person_Person_Cond) RETURN person { .name,friends:[(person)-[:knows]->(personFriends:Person) | personFriends { .name }],pets:[(person)-[:knows]->(personPets:Pet) | personPets { .name }] } AS person
```
which throws the following error:
```
Neo.ClientError.Statement.SyntaxError: Invalid input ']': expected whitespace, comment or an expression (line 1, column 94 (offset: 93))
"MATCH (person:Person) WHERE  ANY(person_Person_Cond IN [(person)-[:knows]->(person_Person) | ] WHERE person_Person_Cond) RETURN person { .name,friends:[(person)-[:knows]->(personFriends:Person) | personFriends { .name }],pets:[(person)-[:knows]->(personPets:Pet) | personPets { .name }] } AS person"
```

**Comment by johnymontana** [comment]
FYI - this use case is covered in neo4j-graphql.js 

See [an example in the tests](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/test/tck/filterTck.md#related-node-does-not-exist)

and [some example use cases in this issue](https://github.com/neo4j-graphql/neo4j-graphql-js/issues/105#issuecomment-487607700)

**Comment by jexp** [comment]
Thanks @johnymontana

**Comment by rgruener** [comment]
I am needing this feature for an internal project. I might have some time to help out implementing it though obviously I am not familiar with the project at all so if I could be pointed in the right direction for fixing this maybe I can take a crack at it.

**Comment by Andy2003** [comment]
@nmonterroso / @rgruener Can you please take a look at PR #179. I would say that the requested queries can currently be handled with the current master version.
