### ISSUE TITLE
Getting wrong Result with outgoing/incoming relationship with same type

### ISSUE THREAD

**Issue by rajankit296** [neo4j-graphql/neo4j-graphql-java#293]
We have added a Schema where we have incoming/outgoing relationship with same type. When we try to fetch result from graphql query, we get opposite result. Instead of outgoing node details, we are getting incoming node details. 

***GraphQL schema***

```
type ActionType{
    id: String!
    outgoingActionTypeRel: [OutGoingActionTypeRelationship]
}

type OutGoingActionTypeRelationship @relation(name:"HAS", from:"actionType", to:"actionType" direction: OUT){
    id: String
    actionType: ActionType
}
```

***GraphQL request***

```
query{
  actionType{
    id
    outgoingActionTypeRel{
      id
      actionType{
        id
      }
    }
  }
}
```

***Generated Cypher***

```
MATCH (actionType:ActionType)
CALL {
	WITH actionType
	MATCH (actionType)<-[actionTypeOutgoingActionTypeRel:HAS]-(actionTypeOutgoingActionTypeRelActionType:ActionType)
	RETURN collect(actionTypeOutgoingActionTypeRel {
		.id,
		actionType: actionTypeOutgoingActionTypeRelActionType {
			.id
		}
	}) AS actionTypeOutgoingActionTypeRel
}
RETURN actionType {
	.id,
	outgoingActionTypeRel: actionTypeOutgoingActionTypeRel
} AS actionType
```

Here, the direction of "actionTypeOutgoingActionTypeRel" should be from "actionType" to "actionTypeOutgoingActionTypeRelActionType"

but it is generating opposite.

**Comment by rajankit296** [comment]
@Andy2003 
Here, we want to fetch outgoing nodes but we are not able to proceed due to this issue.
Can you please help here? 
Thanks

**Comment by Andy2003** [comment]
You should define the rich-relation type `OutGoingActionTypeRelationship` with two different named fields, one for the start-node and one for the end-node of the relation, e.g.:

```graphql
type OutGoingActionTypeRelationship @relation(name:"HAS", from:"from", to:"to" direction: OUT){
    id: String
    from: ActionType
    to: ActionType
}
```

having just one field used both, for `from` and `to` is a misconfiguration.

If you don't need rich-relations, you can also define the relation directly on the field. Please take a look at the [examples](https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/core/src/test/resources/issues/gh-45.adoc).

**Comment by Andy2003** [comment]
Take a look at [this example](https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/core/src/test/resources/relationship-tests.adoc) on how to configure the relation correctly!
