### ISSUE TITLE
not able to sort based on relationship object

### ISSUE THREAD

**Issue by rajankit296** [neo4j-graphql/neo4j-graphql-java#294]
We try to get sorted result based on name present inside resource inside relatesTo. but did not got any way.

```
query  {
     node{
      id,
      relatesTo {
        resource {
          id,
          name
        }
      }
    }
}

```

Schema

```
type Node {
      id: String!
      name: String
      relatesTo: [Relationship] @relation
}

type Resource {
      id: String!
      name: String
}

type Relationship @relation(from:"node", to:"resource", direction: OUT)  {
      id: String!
      resource: Resource
}
```

**Comment by Andy2003** [comment]
If I interpret the description in the ticket correctly, you want deep sorting, this is currently not possible, but there is already a ticket for this: https://github.com/neo4j-graphql/neo4j-graphql-java/issues/64
