### ISSUE TITLE
Authorization rules?

### ISSUE THREAD

**Issue by rickardoberg** [neo4j-graphql/neo4j-graphql-java#298]
We need to perform authorization checks for what data a user is able to see/process/return. What is the recommended way to add such rules with this library? Is there a built-in mechanism for it, or some kind of transformer option that we could use?

Preferably we would be able to package those rules in a Java predicate which would be invoked as the data is processed by the GraphQL evaluator.

**Comment by Andy2003** [comment]
This is part of the ongoing refactoring / migration to be API-aligned with the JS-Version.

**Comment by rickardoberg** [comment]
Some update on this. In the end we completely replaced QueryHandler with our own Cypher translation, and in doing so we could introduce our authorization rules both for objects and fields.
