### ISSUE TITLE
TypeMismatchError when `queryTypeOfInterfaces` is enabled and there are no nodes in a relationship which uses __typename

### ISSUE THREAD

**Issue by isstabb** [neo4j-graphql/neo4j-graphql-java#311]
**Describe the bug**

```
TypeMismatchError Expected type(s) List(Anything) but got value null of type Null in filter comprehension
```

```
CALL {
	WITH person
	CALL {
		WITH person
		WITH $personNamedColleaguesName AS name, person AS this
		MATCH (this)-[:ACTED_IN]->()<-[:ACTED_IN]-(other) WHERE other.name CONTAINS name RETURN other AS personNamedColleagues
	}
	RETURN collect(personNamedColleagues {
		__typename: head([label IN labels(personNamedColleagues) WHERE label IN $personNamedColleaguesValidTypes]),
		.name
	}) AS personNamedColleagues
}
```

(Taken from `gh-147.adoc`). When `other` is null because there's no relationship, then `labels(personNamedColleagues)` is null as described in considerations: https://neo4j.com/docs/cypher-manual/current/functions/list/#functions-labels

Coalescing the labels with an empty list avoids the error.

```
                projections += head(listWith(label).`in`(coalesce(labels(propertyContainer as? Node
                        ?: throw IllegalStateException("Labels are only supported for nodes")),
                        literalOf<List<Any>>(emptyList<Any>()))).where(label.`in`(parameter)).returning())
```

`gh-147.adoc` already has a relevant example data.

**Comment by Andy2003** [comment]
I cannot reproduce this bug, can you please provide the qraphql request for `gh-147.adoc` to reproduce this bug?

**Comment by isstabb** [comment]
I found out this cannot be reproduced with neo4j as used in this project. The error was found in a "neo4j-compatible" environment and the behavior there is different. Sorry!
