### ISSUE TITLE
Does not work with spring boot 3.2.2.

### ISSUE THREAD

**Issue by rlegorreta** [neo4j-graphql/neo4j-graphql-java#312]
**Describe the bug**
There is incompatibility versions that are used between libraries
                 for spring-boot-starter-graphql and the library neo4j-graphql-java
                 using the same library com.graphql-java. For Spring boot 3.2.2
           If we use springframework.boot 3.2.2 the spring-starter-graphql uses the
           com.graphql-java version 20.1 that it is INCOMPATIBLEand send an run time error  with the version 19.2
           that is used in neo4j-graph-ql

**Comment by Andy2003** [comment]
resolved via #302
