### ISSUE TITLE
Creating parent query combining individual entities

### ISSUE THREAD

**Issue by Palak-K9** [neo4j-graphql/neo4j-graphql-java#314]
### Discussed in https://github.com/neo4j-graphql/neo4j-graphql-java/discussions/313

<div type='discussions-op-text'>

<sup>Originally posted by **Palak-K9** April  3, 2024</sup>
I am trying to build and application using the example - [Spring Boot Graphql Example](https://github.com/neo4j-graphql/neo4j-graphql-java/tree/master/examples/graphql-spring-boot)

I have **Neo4j Database** in which there are various node types like **Fruit, Sweet, Vegetable**. I have defined thier schema in **neo4j.graphql file**. and while running graphiql on browser, I can directly query these nodes with conditions.
For example :-

```{  
  fruits{
    name
    quantity
  }
 }
```
 
 This query gives me the fruit nodes with the mentioned fields.
 I can query the individual entities but I want to get these entities under one name/query. I have tried defining the following in no4j.graphql
 
```
 type Query {
      getItems: [Item]
   }
   
  type Item{
     fruits: [Fruit]
     vegetables: [Vegetable]
     sweets: [Sweet]
     }
 ```
 
 But this is not working. Could someone help me how can I acheive this
     
</div>

**Comment by Andy2003** [comment]
I answered in the discussion #313
