### ISSUE TITLE
Unable to use variables in filters

### ISSUE THREAD

**Issue by kevinamick** [neo4j-graphql/neo4j-graphql-java#33]
This issue seems to be related to https://github.com/neo4j-graphql/neo4j-graphql/issues/95.
I'm using Apollo React which sends a request like:

```
{
  operationName:"Similar",
  variables:{"user":"username"},
  query:"query Similar($user: String!) { 
     user(userDn: $user) {    
          similar {      
               username
         }  
     }
   }"
}
```
Which throws the exception: "Unable to convert graphql.language.VariableReference to Neo4j Value"

**Comment by jexp** [comment]
Thanks a lot for the report 
How do you call/serve the graphql endpoint. 
I thought we’re already resolving the references to the passed in arguments

**Comment by kevinamick** [comment]
So this is actually an issue with my code. Apologies for the false alarm.

I'm serving the graphql endpoint using the neo4j java driver. I take the `Translator.Cypher` object and call `session.run(query.getQuery(), query.getParams())`. It looks like the values of the hashmap getParams() returns are the `graphql.language.VariableReference` it's complaining about. 

Do you have any suggestions on how to go about handling this?

**Comment by jexp** [comment]
Fixing it.
