### ISSUE TITLE
Refactor to DSL Pattern

### ISSUE THREAD

**Issue by imkleats** [neo4j-graphql/neo4j-graphql-java#34]
Is there any taste for implementing the Cypher query builder through a DSL?  Kotlin affords us "the ability to create type-safe domain-specific languages (DSLs) suitable for building complex hierarchical data structures in a semi-declarative way" (https://kotlinlang.org/docs/reference/type-safe-builders.html), which screams Cypher and GraphQL to me.

I'm seeing a lot of feature requests that would be quite a bit more manageable with a more expressive and SOLID implementation, but maybe I'm missing something.

**Comment by jexp** [comment]
Yep sure. If you want to give it a try I’d be happy to accept any PR

I did dsls for Cypher in the past. 

Would be good if the dsl (builder) fit well into the translation recursion 

I guess it could be something embedded in the Cypher class

**Comment by imkleats** [comment]
I actually wonder, under a DSL pattern, how important it would be to keep
the query builder within that recursion. The GraphQL query is an AST, and
when that query is converted to the DSL, it will be... an AST of the same
ordinal depth and structure. I wonder if, rather than breaking down the gql
AST and reconstructing, it would instead be possible (or more efficient) to
map straight across the two ASTs.

**Comment by jexp** [comment]
Unfortunately there is no way of directly sending an ast through bolt. 

The transformation would build up the semantic model within the dsl which we can render at the end to a query string. 

Von meinem iPhone gesendet

**Comment by imkleats** [comment]
I get that, but it seems there must have been a gap in what I was trying to
say - apologies for the confusion.  Of course, the DSL would build a string
(i.e. cypher query) that would be fed through bolt.

What I was getting at is that the structure of the complete DSL statement
(prior to transpilation to that string) not only would effectively be an
AST, it would be an AST of the same depth/structure as the GraphQL query's
AST.

This opens the door for some rather elegant approaches to generating the
DSL. On the Selections, for instance, you wouldn't have to even establish
an explicit recursive call within the primary function; the same
"recursion" would implicitly occur when its selection elements are
processed. This would separate concerns even more.

**Comment by jexp** [comment]
we started to use opencypher-dsl in some recent work. hope that is more what you were looking for?

**Comment by jexp** [comment]
So we could make those also available at some point to downstream consumers
