### ISSUE TITLE
How to disable auto generated mutation/query?

### ISSUE THREAD

**Issue by surajrrao** [neo4j-graphql/neo4j-graphql-java#39]
Hi @jexp 

As per the documentation, we can disbale auto generated multations & queries via API - but how to do it? Can you please point me to the java doc or some samples? Thank you in advance!

**Per Documentation**

_Auto Generate Queries and Mutations

To reduce the amount of boilerplate code a user has to write we auto-generate top-level CRUD queries and mutations for all types.

This is configurable via the API, you can:

disable auto-generation (for mutations/queries)

disable it per type

disable mutations per operation (create,delete,update)_

**Comment by surajrrao** [comment]
@jexp Also, is there a way to remove null attributes from the response

**Comment by jexp** [comment]
If you look at the tests you see how it's done there is a context object that you can pass in where you can enabled it per type or globally.

https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/src/test/kotlin/org/neo4j/graphql/AugmentationTest.kt#L51

**Comment by jexp** [comment]
ping?

**Comment by surajrrao** [comment]
that worked!
