### ISSUE TITLE
lack of filtering for null values

### ISSUE THREAD

**Issue by lilianaziolek** [neo4j-graphql/neo4j-graphql-java#47]
It does not seem to be possible to filter using a null value for a property. For example, the following test fails if pasted into FilterTest:

```kotlin
    @Test
    fun testFilterNull(){
        val query = """{ company (name: null) {employees {gender}}}"""
        val expected = """MATCH (company:Company) WHERE company.name IS NULL RETURN company { employees:[(company)<-[:WORKS_AT]-(companyEmployees:Person) | companyEmployees { .gender }] } AS company"""

        assertQuery(schema, query, expected)
    }
```

The generated query contains `company.name = $companyName` instead of `company.name IS NULL`. This does not work in Neo4j if the value is null. Is there alternative syntax that should be used for such query, or is this a bug?

**Comment by jexp** [comment]
Good point.

So would you expect something . like: `filter: { name_is_null : true }` or just `filter: {name: null}`

in the former case we can generate it correctly no matter what, in the latter case we need to look at the passed in value.

**Comment by lilianaziolek** [comment]
yes, both might work, however, I also discovered another related issue (not raised yet) which is that sorting stops working if you have properties with underscores in your Neo4j... (I'm guessing you just split on _ ? ) - so whilst in principle it might work, you'd have to be careful to make sure that e.g. first_name_is_null still works :)

**Comment by lilianaziolek** [comment]
Also, one disadvantage for the former (name_is_null) vs the latter (name: null) is that then you can't have a single graphql query but you need to do some magic to change the query client side, depending on parameter values. So you coudn't have name: $name where you pass in the valye dynamically. 
It's of course doable but  less ideal, and it feels like it's a side-effect of how Neo4j handles nulls internally - rather than how I'd expect it from sort of storage-agnostic (GraphQL) query. So in some ways, it leaks internals of neo4j to the client.

**Comment by jonasdumas** [comment]
+1 
Hello, I would need such filter too

**Comment by alphadever** [comment]
+1 
any updates on this?
