### ISSUE TITLE
performance issues of deep filters

### ISSUE THREAD

**Issue by jexp** [neo4j-graphql/neo4j-graphql-java#63]
deep filters don't use the indexes but do label scan + filter

i.e. currently we generate `ALL(expr IN [(start)-->(next:Next) | next.name = $foo] WHERE expr)`

and nested variants of this for each level of nested filters

* we also do `NONE/SINGLE/SOME(expr ...)`

which we had to generate because:

1. we need the names to express arbitrary predicates and to drill down deeper
2. I didn't think on how to represent ALL except of list of all expression results has to be true

but that leads to indexes not being used

we can change this to: `size([(start)-->(next:Next) WHERE next.name = $foo | true]) = 0` where the `= 0` depends on the below

* ANY(some): size > 1
* SINGLE: size = 1
* NONE: size = 0
* ALL: size = 0 with inverted condition

this works a bit for single level but for deeper nesting it breaks the planner

one idea is to skip intermediate levels if there are no additional filters

e.g.  `size([(start)-->(middle)-->(next:Next) WHERE next.name = $foo | true]) = 0`

originally we would generate:

 `size([(start)-->(middle) WHERE size([(middle)-->(next:Next) WHERE next.name = $foo | true]) = 0 | true]) = 0`

in 4.0 we can generate existential subqueries to help with that

`WHERE exists { MATCH ... WHERE ... } ` I think will be the syntax.

**Comment by jexp** [comment]
This still uses the index:

```
profile MATCH (t:User) WITH collect(t) as users
WHERE size([(t)-[:FOLLOWS]->()-[:FOLLOWS]->(u:User) WHERE u.id = "PunkAB" | u]) = 0
RETURN count(*)
```

![plan-nested-index](https://user-images.githubusercontent.com/67427/65592126-45265180-df8e-11e9-8195-ecfed7801b8e.png)

**Comment by jexp** [comment]
This also still uses the index

```
profile MATCH (t:User) with t limit 10
WHERE size([(t)-[:FOLLOWS]->(b:User) WHERE size([(b)-[:FOLLOWS]->(u:User) WHERE u.id = "PunkAB" | true])=0 | true]) = 0
RETURN count(*)

```

![plan-index-2](https://user-images.githubusercontent.com/67427/65592449-ddbcd180-df8e-11e9-9d83-ad9ade0ed987.png)

**Comment by jexp** [comment]
Problem is with the negation for ALL that kills the index :(

```
profile MATCH (t:User) with t limit 10
WHERE size([(t)-[:FOLLOWS]->(b:User) WHERE size([(b)-[:FOLLOWS]->(u:User) WHERE NOT u.id = "PunkAB" | true])=0 | true]) = 0
RETURN count(*)
```

![plan-3](https://user-images.githubusercontent.com/67427/65596178-a3efc900-df96-11e9-850f-1f69474ae815.png)

**Comment by DirkMahler** [comment]
Thanks a lot!
