### ISSUE TITLE
Invalid parameter names for range queries

### ISSUE THREAD

**Issue by DirkMahler** [neo4j-graphql/neo4j-graphql-java#71]
Given the following type...

```
type Person {
  name: String!
  age: int!
}
```

... I want to execute a range query:

```
Person(filter: {
  age_gte: 20
  age_lt: 30
}) {
  name
}
```
The query currently returns an empty result, as the given parameters in the filter are collapsed into one `filterPersonAge`. The solution would be to use the full filter attribute name, e.g. ` filterPersonAge_gte` and `filterPersonAge_lt`.

**Comment by jexp** [comment]
Great find, thanks Dirk

@Andy2003 could you have a look at that please?

**Comment by DirkMahler** [comment]
Already working on it, I'll provide a PR for this.
