### ISSUE TITLE
Schema Documentation not available in GraphiQL

### ISSUE THREAD

**Issue by Anunayth** [neo4j-graphql/neo4j-graphql-java#74]
I am not able to get the schema doc in Documentation in GraphiQL when the code is run for java. is there any configuration settings to be changed to get schema doc?

**Comment by Anunayth** [comment]
Adding more information to the mentioned question.

I am trying to run neo4j-graphql-java integrating it with Spring Boot. On running so, the Introspection queries are not working.

The query "__schema" throws error saying 

" java.lang.IllegalArgumentException: Unknown Query __schema available queries: 
	at org.neo4j.graphql.Translator.toQuery(Translator.kt:70)
	at org.neo4j.graphql.Translator.translate(Translator.kt:48)"
	
I tried to run the same with the server.groovy, but i could not fetch any information for the introspection.
I am not able to figure out if any configuration needs to be set in order to get the information for introspection queries.

**Comment by Andy2003** [comment]
you have to pass through these introspection queries directly to the graphql schema like here:

https://github.com/neo4j-graphql/neo4j-graphql-java/blob/249877ddd05d36a8a7030133f5023f1f0e02861a/src/test/kotlin/GraphQLServer.kt#L75-L76
