### ISSUE TITLE
Internal Neo4J ID being returned as null

### ISSUE THREAD

**Issue by AlexPresso** [neo4j-graphql/neo4j-graphql-java#76]
When using the following schema: 
```graphql
type BaseNode {
  _id: ID!
  createdAt: String
  icon: String
  name: String
}
```

In the following Javalin Handler (the Session is created by the Neo4J OGM, on Neo4J 4.0):
```java
public boolean asyncTask(ApiCompletableFuture api, Context context, Session session) throws Exception {
     Map<Object, Object> json = ApiUtils.deserialize(context.body());

     if(!json.containsKey("query"))
         throw new ApiException("Empty query");

     Translator graphql = new Translator(SchemaBuilder.buildSchema(GraphQL.getSchema(), new Translator.Context()));

     Map<Object, Set<Object>> results = graphql.translate(json.get("query").toString()).stream()
         .flatMap(cypher -> StreamSupport.stream(session.query(cypher.getQuery(), cypher.getParams()).spliterator(), false))
         .flatMap(streamMap -> streamMap.entrySet().stream())
         .collect(Collectors.groupingBy(Map.Entry::getKey, Collectors.mapping(Map.Entry::getValue, Collectors.toSet())));

     return api.success("Query result", results);
}
```

Is always giving null IDs, is there something I'm doing wrong ?
```json
{
    "data": {
        "baseNode": [
            {
                "name": "Test",
                "_id": null
            }
        ]
    },
    "message": "Query result",
    "errors": null
}
```

**Comment by Andy2003** [comment]
Please provide:

* The version of neo4j-graphql-java you use
* the schema
* the graphql query
* the resulting cypher query

In general the usage of native ID is also covered by tests: https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/src/test/resources/filter-tests.adoc#filter-on-nativeid

**Comment by AlexPresso** [comment]
Thanks for the reply, here are the informations:

- neo4j-graphql-java 1.0.0-M03 (from [this maven repo](https://mvnrepository.com/artifact/org.neo4j/neo4j-graphql-java/1.0.0-M03))
- Here is the [schema.graphql](https://gist.github.com/AlexPresso/451f3fee6d677dcddbab79e9c8f06dfa)
- Here is the query: [postman query](https://gist.github.com/AlexPresso/8e87a4ca3709dd0ae921c1963de1a81a)
- Here is the CypherQuery from debugger: 
`MATCH (baseNode:BaseNode) RETURN baseNode { .name,._id } AS baseNode LIMIT 2`

**Comment by Andy2003** [comment]
@AlexPresso It seems, that this feature is not yet released, you have to build a custom build from master or wait for the next release.

cc @jexp

**Comment by AlexPresso** [comment]
Do you have an ETA for the next release ? just to know if I can wait for it or need to implement my own build

**Comment by Andy2003** [comment]
There will will be a new release around the end of this month.
