### ISSUE TITLE
Filter with Datetime (Temporal) not working

### ISSUE THREAD

**Issue by Techyoga1990** [neo4j-graphql/neo4j-graphql-java#93]
I am trying to filter data using date time but Neo4J translator is not creating correct query, i am not sure if this is bug or feature is missing. 

I have schema like below :- 

```
type Person{
name: String
born: _Neo4jDateTime
} 
```

i am using below query using filter :- 

```
{
person(filter: {born: {year_gt: 2010} }){
name
born{
formatted
}
}
}
```

below Cyper is getting created :- 

```
MATCH(person:Person) where person.born > $filterPersonBorn_GT
RETURN ....

```
year is not getting considered in query. 

Can you please help me right query for date time filter or if there any workaround for this issue.

**Comment by Andy2003** [comment]
This type of filtering for temporal types is not yet implemented and there is currently no workaround to get it working.
I will have a look at this issue.

**Comment by jexp** [comment]
could we implement this by using the accessory like `born.year > $x `

**Comment by Andy2003** [comment]
as pointed out in https://github.com/neo4j-graphql/neo4j-graphql-java/pull/229#issuecomment-845288588, the way to filter dates / times should be refactored to macht the logic of the js version.

This means, we remove the date-/time-related types and use scalars (iso strings) instead
