### ISSUE TITLE
integration in JAVA

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j-graphql/neo4j-graphql-java#97]
Are there any examples of integration in JAVA? I have encountered some problems in integration and would like to refer to them.I want to see the parsing processes.

How to use spring-boot integration .

**Comment by rbramley** [comment]
I got it working in Spring Boot in conjunction with `com.graphql-java:graphql-java-spring-boot-starter-webmvc` (starting from the _graphql-java book-details_ SpringBoot tutorial app). 
Definitely agree that more documentation / examples would be helpful!

I based my logic on the _Server.groovy_ example, the necessary steps were:

1. Add the `neo4j-graphql-java` and `neo4j-java-driver` dependencies
2. Modify the `schema.graphqljs` to reflect the Neo4j schema (and add `@relation` directives etc.)
3. Modify the `GraphQLProvider.buildSchema` to use the Neo4j `SchemaBuilder`
4. Create a new `GraphQLInvocation` implementation (needs the `@Primary` annotation as well as `@Component`) that invokes the `Translator` and runs the query on the `session`.

**Comment by Andy2003** [comment]
relates to #119
