### ISSUE TITLE
Relationship mutations are not using the correct direction

### ISSUE THREAD

**Issue by ZikFat** [neo4j-graphql/neo4j-graphql-java#98]
I have a database with nodes like this:

![graph](https://user-images.githubusercontent.com/1429840/88980808-52306300-d279-11ea-975a-11c6a9df39ca.png)

And a graphql schema like this:

```
type Team {
  id: ID!
  name: String!
  players: [Player!]! @relation(name: "MEMBER_OF", direction: IN)
}

type Player {
  id: ID!
  name: String!
  teams: [Team] @relation(name: "MEMBER_OF")
}
```

The cypher queries generated when I run the deleteTeamPlayers and addTeamPlayers mutations are specifying the relationship in the wrong direction.

Here's the cypher generated by deleteTeamPlayers:

> RUN "MATCH (from:Team { id: $fromId }) MATCH (to:Player) WHERE  to.id IN $toPlayers **MATCH (from)-[r:MEMBER_OF]->(to)** DELETE r WITH DISTINCT from AS deleteResult RETURN deleteResult { .name } AS deleteResult"

And here's addTeamPlayers:

> RUN "MATCH (from:Team { id: $fromId }) MATCH (to:Player) WHERE  to.id IN $toPlayers **MERGE (from)-[:MEMBER_OF]->(to)** WITH DISTINCT from AS addResult RETURN addResult { .name } AS addResult"

These queries are building MATCH and MERGE clauses going from Team to Player even though my graphQL schema and database have the relationships going from Player to Team. The result is that the deleteTeamPlayers mutation doesn't do anything since it can't find any relationships to match on, and the addTeamPlayers mutation adds a relationship in the opposite direction of what's desired.

The deletePlayerTeams and addPlayerTeams mutations that were generated from the Player type work fine. It seems like the problem is that these relationship mutations are always using an outbound direction.

**Comment by jexp** [comment]
Thanks for reporting that is an  really unexpected bug.

**Comment by jexp** [comment]
As we have a TCK test here:

https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/src/test/resources/movie-tests.adoc#should-auto-generate-add-relationship-mutations-for-arrays

**Comment by jexp** [comment]
But you are correct, we don't test it in the inverse direction and the arrow here is hardcoded @Andy2003 

https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/src/main/kotlin/org/neo4j/graphql/handler/relation/DeleteRelationHandler.kt#L54

Probably the same for the MERGE / CREATE handler
